### ISSUE TITLE
[Request] Add Medium weight.

### ISSUE THREAD

**Issue by roidy** [realcopacetic/resource.fonts.copacetic#5]
Any chance you could add the Medium weight version of this font, Thanks

**Comment by realcopacetic** [comment]
Sure I can do that. For KR, SC or both

**Comment by roidy** [comment]
Thanks, I only really need KR but if you've got time adding SC would keep the resource the same across both font sets.

**Comment by realcopacetic** [comment]
Added in 1.0.5

**Comment by roidy** [comment]
Thanks really appreciate that 👍

**Comment by realcopacetic** [comment]
No worries if you update from my repo, the latest versions of everything should be available. It may take a little while to get bit updated on the official repo asy latest update is failing the automated github check and I can't figure out why!

**Comment by realcopacetic** [comment]
Hey @roidy  - I had a bit of an ordeal after I added the Medium fonts to this repository then tried to update my main repo, as it pushed the zip files past the 100MB Github limit. I tried Git LFS, but it doesn't actually host the zip files in a way that Kodi can grab them unless you change a config setting ,and then that turned out to mean you only get 1GB bandwidth a month before you have to pay.

The long and short of it is that you may notice the medium fonts aren't available via resource.fonts.copacetic in Kodi if you install the addon via my repository. They will still be available here on Github if you just needed to grab them for your own project and I've submitted the update including medium font weights to the official kodi repo so once that is live they'll be available there as well.

Just wanted to let you know in case you noticed the discrepancy. It's a bit annoying, but I couldn't think of a better way to handle it in the short term at least, beyond splitting this into two separate repositories. But seeing as I don't need Medium for my skin and my repo is only really geared towards that, I think it's ok. Anyone who needs access to these fonts via Kodi would probably want to rely on the official repo anyway!

**Comment by roidy** [comment]
Thanks for letting me know, I haven't had a chance to try and grab them or test them yet, really busy at work. I'll just grab them from github over the weekend to use until they go live in the official repo. Again thank for taking the time to sort all this 👍

**Comment by roidy** [comment]
Just to say they are live on the official repo now and work great. Again thanks for the medium weight 👍
